/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usfirst_frc_team1719_pixyjni_PixyJNI */

#ifndef _Included_org_usfirst_frc_team1719_pixyjni_PixyJNI
#define _Included_org_usfirst_frc_team1719_pixyjni_PixyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_init
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    blocksAreNew
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_blocksAreNew
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getAutoExposureCompensation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getAutoExposureCompensation
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getAutoWhiteBalance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getAutoWhiteBalance
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getBrightness
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getBrightness
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getExposureCompensastion
 * Signature: (Lorg/usfirst/frc/team1719/pixyjni/IntPtr;Lorg/usfirst/frc/team1719/pixyjni/IntPtr;)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getExposureCompensastion
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getWhiteBalanceValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getWhiteBalanceValue
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    setAutoExposureCompensation
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_setAutoExposureCompensation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    setAutoWhiteBalance
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_setAutoWhiteBalance
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    setBrightness
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_setBrightness
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    setExposureCompensation
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_setExposureCompensation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    setWhiteBalanceValue
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_setWhiteBalanceValue
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_close
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    command
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_command
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getBlocks
 * Signature: (I[Lorg/usfirst/frc/team1719/pixyjni/Block;)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getBlocks
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    getFirmwareVersion
 * Signature: (Lorg/usfirst/frc/team1719/pixyjni/IntPtr;Lorg/usfirst/frc/team1719/pixyjni/IntPtr;Lorg/usfirst/frc/team1719/pixyjni/IntPtr;)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_getFirmwareVersion
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    ledGetMaxCurrent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_ledGetMaxCurrent
  (JNIEnv *, jobject);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    ledSetMaxCurrent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_ledSetMaxCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_usfirst_frc_team1719_pixyjni_PixyJNI
 * Method:    ledSetRGB
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_usfirst_frc_team1719_pixyjni_PixyJNI_ledSetRGB
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
